env:
  global:
  - REPO_DIR=python-driver
  - BUILD_COMMIT=f5001b8759d34896a1899b791a5ca57db8ba8069
  - BUILD_DEPENDS="geomet>=0.1,<0.3 six>=1.9 futures<=2.2.0 Cython>=0.20,!=0.25,<0.30"
  - TEST_DEPENDS=""
  - UNICODE_WIDTH=32
  - MB_ML_VER=1
language: python
python: 3.5
os: linux
dist: xenial
services: docker
jobs:
  include:
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.7
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.7
    - PLAT=i686
  - arch: arm64
    os: linux
    services: docker
    env:
    - MB_PYTHON_VERSION=3.7
    - MB_ML_VER=2014
    - PLAT=aarch64
    - DOCKER_TEST_IMAGE=multibuild/xenial_arm64v8
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.8
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.8
    - PLAT=i686
  - arch: arm64
    os: linux
    services: docker
    env:
    - MB_PYTHON_VERSION=3.8
    - MB_ML_VER=2014
    - PLAT=aarch64
    - DOCKER_TEST_IMAGE=multibuild/xenial_arm64v8
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.9
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.9
    - PLAT=i686
  - arch: arm64
    os: linux
    services: docker
    env:
    - MB_PYTHON_VERSION=3.9
    - MB_ML_VER=2014
    - PLAT=aarch64
    - DOCKER_TEST_IMAGE=multibuild/xenial_arm64v8
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.10
    - MB_ML_VER=2010
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.10
    - MB_ML_VER=2010
    - PLAT=i686
  - arch: arm64
    os: linux
    services: docker
    env:
    - MB_PYTHON_VERSION=3.10
    - MB_ML_VER=2014
    - PLAT=aarch64
    - DOCKER_TEST_IMAGE=multibuild/xenial_arm64v8
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.11
    - MB_ML_VER=2014
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.11
    - MB_ML_VER=2014
    - PLAT=i686
  - arch: arm64
    os: linux
    services: docker
    env:
    - MB_PYTHON_VERSION=3.11
    - MB_ML_VER=2014
    - PLAT=aarch64
    - DOCKER_TEST_IMAGE=multibuild/xenial_arm64v8
script: bash build_wheel.sh