env:
  global:
  - REPO_DIR=python-driver
  - BUILD_COMMIT=15d715f4e686032b02ce785eca1d176d2b25e32b
  - BUILD_DEPENDS="geomet>=0.1,<0.3 six>=1.9 futures<=2.2.0 Cython>=0.20,!=0.25,<0.30"
  - TEST_DEPENDS=""
  - UNICODE_WIDTH=32
  - MB_ML_VER=1
language: python
python: 3.5
os: linux
dist: xenial
services: docker
jobs:
  include:
  - os: linux
    env: MB_PYTHON_VERSION=2.7
  - os: linux
    env:
    - MB_PYTHON_VERSION=2.7
    - UNICODE_WIDTH=16
  - os: linux
    env:
    - MB_PYTHON_VERSION=2.7
    - PLAT=i686
  - os: linux
    env:
    - MB_PYTHON_VERSION=2.7
    - PLAT=i686
    - UNICODE_WIDTH=16
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.5
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.5
    - PLAT=i686
  - os: osx
    osx_image: xcode11
    language: generic
    env:
    - MB_PYTHON_VERSION=2.7
  - os: osx
    osx_image: xcode11
    language: generic
    env:
    - MB_PYTHON_OSX_VERSION=10.6
    - PLAT=x86_64
    - MB_PYTHON_VERSION=3.5
script: bash build_wheel.sh